### ISSUE TITLE
Add Github Actions Workflow

### ISSUE THREAD

**Issue by felipemfp** [lab259/athena#10]
**Briefing**

A GitHub Actions Workflow in this repository would be very nice!

**Tasks**

* [ ] Add a GH Actions Workflow (based on this [one](https://github.com/lab259/errors/blob/master/.github/workflows/go.yml))

**Comment by sdesani** [comment]
Hi @felipemfp, I would like to contribute on this one.

**Comment by sdesani** [comment]
Created PR for same - https://github.com/lab259/athena/pull/11
